#!/bin/bash

msgId=$RANDOM

initialState=$(cat $HOME/.batteryrc)

while :
    do
        batteryState=$(acpi -b | awk '{print $3}' | sed 's/[^a-zA-Z]*//g')

        case $batteryState in

            ($initialState) ;;

            (*)
                dunstify -a "Charger" -u low -i charger-changed -r $msgId "Charging Status Changed: ${batteryState}"
                initialState=$batteryState
                echo $initialState > $HOME/.batteryrc

                ;;

        esac

        sleep 30
    done 

