#!/bin/bash

#i3-msg "workspace 5; append_layout ~/.config/i3/workspace_5.json"
i3-msg "workspace 4; append_layout ~/.config/i3/workspace_4.json"
i3-msg "workspace 3; append_layout ~/.config/i3/workspace_3.json"
i3-msg "workspace 2; append_layout ~/.config/i3/workspace_2.json"
i3-msg "workspace 1; append_layout ~/.config/i3/workspace_1.json"

