#!/bin/bash


MUTED=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')

if [[ $MUTED == "yes" ]]; then
    newValue=1
else
    newValue=0
fi

brightnessctl --device=platform::micmute set $newValue > /dev/null 2>&1

