#!/bin/bash


MUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

if [[ $MUTED == "yes" ]]; then
    newValue=1
else
    newValue=0
fi

brightnessctl --device=platform::mute set $newValue > /dev/null 2>&1

