format = """
$username\
$hostname\
$jobs\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$time\
$python\
$character"""

[jobs]
symbol_threshold = 1
number_threshold = 1
format = '[\[$symbol$number\]]($style) '

[directory]
style = "blue"
truncation_length = 8
truncation_symbol = ".../"
truncate_to_repo = false
read_only = "X"
format = '[$path]($style) [$read_only]($read_only_style)'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[time]
format = '[$time]($style) '
style = 'bold white'
disabled = false

[python]
format = "[$virtualenv]($style)"
style = "yellow"
